config/routes.rb
Refinery::Core::Engine.routes.draw do
  root to: 'pages#home', via: :get
  get '/pages/:id', to: 'pages#show', as: :page

  namespace :pages, path: '' do
    namespace :admin, path: Refinery::Core.backend_route do
      scope path: :pages do
        post 'preview', to: 'preview#show', as: :preview_pages
        patch 'preview/*path', to: 'preview#show', as: :preview_page
      end
    end
  end

  namespace :admin, path: Refinery::Core.backend_route do
    get 'pages/*path/edit', to: 'pages#edit', as: 'edit_page'
    get 'pages/*path/children', to: 'pages#children', as: 'children_pages'
    patch 'pages/*path', to: 'pages#update', as: 'update_page'
    delete 'pages/*path', to: 'pages#destroy', as: 'delete_page'

    resources :pages, except: :show do
      post :update_positions, on: :collection
    end

    resources :pages_dialogs, only: [] do
      collection do
        get :link_to
      end
    end

    resources :page_parts, only: [:new, :create, :destroy]
  end
end

app/views/refinery/admin/pages/_actions.html.erb
<ul>
  <li><%= render '/refinery/admin/search', url: refinery.admin_pages_path -%></li>
  <li>
    <%= action_label :add, refinery.new_admin_page_path, t('.create_new_page') %>
  </li>
<% if @pages.many? and !searching? %>
  <li>
    <%= action_label :reorder, refinery.admin_pages_path, t('.reorder_pages'), id: 'reorder_action'%>
    <%= action_label :reorder_done, refinery.admin_pages_path, t('.reorder_pages_done'), id: 'reorder_action_done', class: 'hidden'%>
  </li>
<% end %>
</ul>

app/views/refinery/admin/pages/_form_advanced_options.html.erb
<%= render '/refinery/admin/form_advanced_options_menu', :f => f %>

<div id="more_options" style="display:none;">
  <div class="hemisquare">
    <h2><%= t('.page_options') %></h2>
    <div class='field'>
      <span class='label_with_help'>
        <%= f.label :parent_id, t('.parent_page') %>
        <%= refinery_help_tag t('.parent_page_help')%>
      </span>
      <%= f.select :parent_id, parent_id_nested_set_options(@page), :include_blank => true %>
    </div>
    <% if Refinery::Pages.use_layout_templates %>
    <div class='field'>
      <span class='label_with_help'>
        <%= f.label :layout_template, t('.layout_template') %>
        <%= refinery_help_tag t('.layout_template_help') %>
      </span>
      <%= f.select :layout_template, valid_layout_templates,
                   template_options(:layout_template, @page) %>
    </div>
    <% end %>
    <div class='field'>
      <span class='label_with_help'>
        <%= f.label :view_template, t('.view_template') %>
        <%= refinery_help_tag t('.view_template_help') %>
      </span>
      <%= f.select :view_template, valid_view_templates.map { |t| [t.titleize, t] },
                   template_options(:view_template, @page) %>
    </div>

    <div class='field'>
      <span class='label_with_help'>
        <%= f.label :menu_title, t('.menu_title') %>
        <%= refinery_help_tag t('.menu_title_help') %>
      </span>
      <%= f.text_field :menu_title, :style=> 'width:400px;' %>
    </div>
    <% if Refinery::Pages.use_custom_slugs %>
    <div class='field'>
      <span class='label_with_help'>
        <%= f.label :custom_slug, t('.custom_slug') %>
        <%= refinery_help_tag t('.custom_slug_help') %>
      </span>
      <%= f.text_field :custom_slug, :style=> 'width:400px;' %>
    </div>
    <% end %>
    <div class='field'>
      <span class='label_with_help'>
        <%= f.label :skip_to_first_child?, t('.skip_to_first_child') %>
        <%= refinery_help_tag t('.skip_to_first_child_help') %>
      </span>
      <%= f.check_box :skip_to_first_child %>
      <%= f.label :skip_to_first_child, t('.skip_to_first_child_label'),
                  :class => "stripped" %>
    </div>
    <div class='field'>
      <span class='label_with_help'>
        <%= f.label :link_url, t('.link_url') %>
        <%= refinery_help_tag t('.link_url_help') %>
      </span>
      <%= f.text_field :link_url, :style=> 'width:400px;' %>
      <% content_for :javascripts do %>
      <script>
        $(document).ready(function(){
          link_tester.validate_url_textbox("#page_link_url")
        });
      </script>
      <% end %>
    </div>
    <div class='field'>
      <span class='label_with_help'>
        <%= f.label :show_in_menu, t('.show_in_menu_title'),
                    :id => 'page_show_in_menu_heading' %>
        <%= refinery_help_tag t('.show_in_menu_help') %>
      </span>
      <%= f.check_box :show_in_menu %>
      <%= f.label :show_in_menu, t('.show_in_menu_description'),
                  :class => "stripped" %>
    </div>

    <%= render 'form_extra_fields_for_more_options', :f => f %>
  </div>

  <%= render 'form_advanced_options_seo', :f => f %>
</div>

app/views/refinery/admin/pages/_form_advanced_options_seo.html.erb
<div class="hemisquare right_side">
  <%= render '/seo_meta/form', :form => f %>
</div>

app/views/refinery/admin/pages/_form_extra_fields_for_more_options.html.erb
<%# Intentionally empty, useful override point to add extra fields. %>

app/views/refinery/admin/pages/_form_new_page_parts.html.erb
<div id='new_page_part_dialog' style='display: none'>
  <div class='field'>
    <label for='new_page_part_title'><%= t('.title')  %></label>
    <input id='new_page_part_title' value='' class='larger widest' />

    <label for='new_page_part_slug'><%= t('.slug')  %></label>
    <input id='new_page_part_slug' value='' class='larger widest' />

    <input id='new_page_part_index' type='hidden' value='<%= @page.parts.size %>' />
  </div>
  <%= render '/refinery/admin/form_actions', :f => f,
             :continue_editing => false,
             :submit_button_id => "new_page_part_save",
             :cancel_button_id => "new_page_part_cancel",
             :hide_delete => true %>
</div>

<% content_for :after_javascript_libraries do %>
  <%= javascript_include_tag 'speakingurl' %>
<% end %>

app/views/refinery/admin/pages/_form_page_parts.html.erb
<% if ::Refinery::Pages.new_page_parts %>
  <ul id="page_parts_controls">
     <li>
      <%= action_icon(:reorder_h, '#', t('.reorder_content_section'), id: 'reorder_page_part' ) %>
      <%= action_icon(:reorder_done, '#',  t('.reorder_content_section_done'), id: 'reorder_page_part_done')%>
    </li>
    <li>
      <%= action_icon(:add, '#', t('.create_content_section'), id: 'add_page_part')%>
    <li>
      <%= action_icon(:delete_section, '#', t('.delete_content_section'), id: 'delete_page_part', class: 'delete_page_part' )  %>
    </li>
  </ul>
<% end %>

<div id='page-tabs' class='clearfix ui-tabs ui-widget ui-widget-content ui-corner-all'>
  <ul id='page_parts'>
    <% @page.parts.each_with_index do |part, part_index| %>
      <li class='ui-state-default<%= ' ui-state-active' if part_index == 0 %>' data-index='<%= part_index %>'>
        <%= link_to part.title, "##{@page.persisted? ? part.to_param : "page_part_new_#{part_index}"}" %>
      </li>
    <% end %>
    <% ::Refinery::Pages.tabs_for_template(@page.view_template).each_with_index do |tab, tab_index| %>
      <li class='ui-state-default' id="custom_<%= tab.name %>_tab">
        <%= link_to tab.name.titleize, "#custom_tab_#{tab_index}" %>
      </li>
    <% end %>
  </ul>

  <div id='page_part_editors'>
    <% part_index = -1 %>
    <%= f.fields_for :parts do |p| %>
      <%= render 'page_part_field',
                 part: p.object,
                 part_index: (part_index += 1),
                 new_part: @page.new_record? -%>
    <% end %>
    <% ::Refinery::Pages.tabs_for_template(@page.view_template).each_with_index do |tab, tab_index| %>
      <div class='page_part' id='<%= "custom_tab_#{tab_index}" %>'>
        <%= render tab.partial, f: f %>
      </div>
    <% end %>
  </div>
</div>

app/views/refinery/admin/pages/_page.html.erb
<% # setup params for various action links
  add_url =   refinery.new_admin_page_path(parent_id: page.page_id)
  edit_url =  refinery.admin_edit_page_path(page.nested_url, switch_locale: :en)
  delete_url = refinery.admin_delete_page_path(page.nested_url)
  delete_options = {
     class: "cancel confirm-delete",
            data: {confirm: t('message',  scope: 'refinery.admin.delete', title: page.title)}
          }
 %>

  <li class='clearfix record items' id="<%= dom_id(page) -%>">
  <div class='clearfix'>
    <% if page.children.present? %>
      <span class="item icon toggle <%= 'expanded' if Refinery::Pages.auto_expand_admin_tree %>"
        title="<%= t('expand_collapse', scope: 'refinery.admin.pages')%>">
      </span>
    <% else %>
      <span class="item"></span>
    <% end %>

    <span class='title <%= 'toggle' if page.children.present? %>'>
      <%= page.title %>
      <%= page_meta_information page %>
    </span>

    <span class='actions'>
      <%= action_icon(:preview, page.url,   t('.view_live_html')) %>
      <%= action_icon(:add,     add_url,    t('new',    scope: 'refinery.admin.pages' ) ) %>
      <%= action_icon(:edit,    edit_url ,  t('edit',   scope: 'refinery.admin.pages' ) ) %>
      <%= action_icon(:delete,  delete_url, t('delete', scope: 'refinery.admin.pages' ), delete_options ) if page.deletable? %>
    </span>
  </div>
  <ul class='nested' data-ajax-content="<%= refinery.admin_children_pages_path(page.nested_url) %>">
    <%= render(partial: 'page', collection: page.children) if Refinery::Pages.auto_expand_admin_tree %>
  </ul>
</li>

app/views/refinery/admin/pages/_records.html.erb
<%= render 'refinery/admin/search_header', :url => refinery.admin_pages_path %>
<% if @pages.any? %>
  <%= render 'sortable_list' %>
<% else %>
  <p>
    <% if searching? %>
      <%= t('no_results', :scope => 'refinery.admin.search') %>
    <% else %>
      <strong><%=t('.no_pages_yet')%></strong>
    <% end %>
  </p>
<% end %>

app/views/refinery/admin/pages/_save_and_continue_callback.html.erb
<%= render '/refinery/message' %>
<%= hidden_field_tag 'new_action', local_assigns[:new_refinery_page_path] %>
<%= hidden_field_tag 'new_refinery_edit_page_path', local_assigns[:new_refinery_edit_page_path] %>
<script>refinery_page_preview_url = '<%= local_assigns[:new_page_path] %>';</script>

app/views/refinery/admin/pages/_sortable_list.html.erb
<ul id='sortable_list'>
  <%= render :partial => 'page', :collection => @pages.roots  %>
</ul>
<%= render '/refinery/admin/sortable_list', :continue_reordering => !!local_assigns[:continue_reordering] %>

app/views/refinery/admin/pages/children.html.erb
<%= render :partial => 'page', :collection => @page.children %>

app/views/refinery/admin/pages/edit.html.erb
<%= render 'form' %>

app/views/refinery/admin/pages/index.html.erb
<section id='records' class='tree'>
  <%= render 'records' %>
</section>
<section id='actions'>
  <%= render 'actions' %>
</section>
<%= render '/refinery/admin/make_sortable', options: {tree: true, replaceContentsAfterUpdate: true} if @pages.many? -%>

app/views/refinery/admin/pages/new.html.erb
<%= render 'form' %>